# Generated by Django 6.0 on 2026-05-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_owner_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='currency',
            field=models.CharField(choices=[('UAH', 'грн'), ('USD', '$'), ('EUR', '€')], default='USD', max_length=10),
        ),
    ]
