# Generated by Django 6.0 on 2026-05-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='acceleration',
            field=models.CharField(default='4.3s', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='power',
            field=models.CharField(default='400 hp', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(default='Manual', max_length=50),
        ),
    ]
