# Generated by Django 6.0 on 2026-05-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_acceleration_car_power_car_transmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('classic', 'Класичні спорткари'), ('hypercar', 'Суперкари та гіперкари'), ('practical', 'Практичні авто')], default='classic', max_length=20),
        ),
    ]
