# Generated by Django 6.0 on 2026-06-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='ID чату в Telegram для отримання заявок', max_length=50, null=True),
        ),
    ]
